### ISSUE TITLE
Trying to get batterytender to work

### ISSUE THREAD

**Issue by cirtbrethren** [jkoelker/batterytender#1]
Hello, thank you for writing this code.  I'm fairly new to Python, and am trying to get your batterytender script to run properly.  I have Python3 installed and have saved the program with my email and password as Deltran.py. 
 When I run `pipenv run python3 Deltran.py` I get the following errors:

`Traceback (most recent call last):
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10f4b3c50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='btconnectedpower.com', port=443): Max retries exceeded with url: /api/users/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f4b3c50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deltran.py", line 8, in <module>
    for monitor in bt.monitors:
  File "/Users/scott/Documents/pythonpractice/batterytender-1.0.1/batterytender/__init__.py", line 305, in monitors
    self.refresh_cache()
  File "/Users/scott/Documents/pythonpractice/batterytender-1.0.1/batterytender/__init__.py", line 291, in refresh_cache
    self._request('POST', LOGIN_PATH)
  File "/Users/scott/Documents/pythonpractice/batterytender-1.0.1/batterytender/__init__.py", line 225, in _request
    allow_redirects=False)
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/scott/.local/share/virtualenvs/batterytender-1.0.1-R8l2dGmb/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='btconnectedpower.com', port=443): Max retries exceeded with url: /api/users/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f4b3c50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
`
Now I certainly don't expect you to teach me Python, but maybe there's something simple I'm missing that can steer me in the right direction.  
Thanks again for writing this.

**Comment by jkoelker** [comment]
Thanks for bringing this to my attention, it looks like sometime the api endpoint got updated and no longer supports ssl (hence the connect timeouts), nor generates 401 for the login path (it now 500's). I've uploaded version 1.1.0 to pypi and the repo, it should fix the issue.
