### ISSUE TITLE
Still having similar errors with the new update

### ISSUE THREAD

**Issue by cirtbrethren** [jkoelker/batterytender#2]
Hi Jason,

I downloaded your updates (batterytender -1.1.0) and I'm still getting similar errors regarding connections.  Here is my output when running:

`Traceback (most recent call last):
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x107da0e10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='btconnectedpower.com', port=80): Max retries exceeded with url: /api/users/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107da0e10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deltran.py", line 8, in <module>
    for monitor in bt.monitors:
  File "/Users/scott/Documents/pythonpractice/batterytender-1.1.0/batterytender/__init__.py", line 304, in monitors
    self.refresh_cache()
  File "/Users/scott/Documents/pythonpractice/batterytender-1.1.0/batterytender/__init__.py", line 290, in refresh_cache
    self._request('POST', AUTHENTICATE_PATH)
  File "/Users/scott/Documents/pythonpractice/batterytender-1.1.0/batterytender/__init__.py", line 224, in _request
    allow_redirects=False)
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/scott/.local/share/virtualenvs/pythonpractice-k8k_MSiE/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='btconnectedpower.com', port=80): Max retries exceeded with url: /api/users/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107da0e10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
`
Thanks for your help.
Scott

**Comment by jkoelker** [comment]
Hrm, the error `nodename nor servname provided, or not known` leads me to suspect a DNS resolution error, can you `curl btconnectedpower.com` ?

**Comment by jkoelker** [comment]
Haven't heard back, so i'm going to close this. If you're still having issues feel free to re-open it.
