### ISSUE TITLE
Can't run sample program [fixed, actually, just posting for reference]

### ISSUE THREAD

**Issue by tgice** [jkoelker/batterytender#3]
Hi, I just installed your package via pip, as indicated, which succeeded.  I'm running python 3.7.1 on Windows, ... and never mind, I figured it out.  Python newbie here, but I suppose I'll post this in case any other such python newbies come along trying to run this project.

The lesson is, don't name your test (or otherwise) script 'batterytender.py', because then it conflicts with importing jkoelker's package.  You'll see something like this:

```
Traceback (most recent call last):
  File "batterytender.py", line 1, in <module>
    import batterytender
  File "C:\batterytender.py", line 6, in <module>
    bt = batterytender.BatteryTender(email, password)
AttributeError: module 'batterytender' has no attribute 'BatteryTender'
```

Thanks for sharing -- this project is one reason that I decided to buy the Battery Tender product over the competing Schumacher product.

Another idea I had too, in case Deltran someday shuts down their servers, but we still have working units in the field: it may be interesting to develop a server you could run on your own network, where you override local DNS to redirect access to the deltran servers to your own internal ones and gather the monitors' reports there.  Not important at the moment, I suppose, except for extreme privacy reasons, but someday, maybe.

Sorry if the issue post is annoying, but I didn't see where else to make these comments other than the Wiki, maybe.

**Comment by jkoelker** [comment]
It looks like the name of the file is `battertender.py`, if that is the case, then its trying to import itself instead of the actual module, try renaming that to `bt.py`.

So I know the devices report via mqtt, but i can't remember if the payload was encrypted or not. If not it would be fairly trivial to capture.

**Comment by jkoelker** [comment]
and, i suck at reading comprehension ;)
